
data:
  kdat: /data/1.0mm_21-dir_R1x3_kdat_slice_010.h5
  navi: null
  slice_idx: 10
  coil: /data/1.0mm_21-dir_R1x3_coils.h5
  dvs: /data/1.0mm_21-dir_R1x3_dvs.h5

model:
  checkpoint: /examples/2024-03-08_vae_1.0mm_21-dir_R1x3_latent-07/train_VAE_Latent07_final.pt
  # checkpoint: /examples/2024-03-07_vae_1.0mm_21-dir_R1x3_latent-07/train_VAE_Latent07_final.pt
  N_latent: 7
