method: zsssl
data:
  kdat: /data/1.0mm_126-dir_R3x3_kdat_slice_000.h5
  navi: null
  slice_idx: 0
  coil: /data/1.0mm_126-dir_R3x3_coils.h5
  normalize_kdat: 1.0
  valid_rho: 0.2
  train_rho: 0.4
  repeats: 15
  batch_size: 1
  N_shot_retro: 0
  N_diff_split: 3
  N_diff_split_index: 2
model:
  net: ResNet2D
  N_residual_block: 12
  unrolled_algorithm: ADMM
  ADMM_rho: 0.05
  N_unroll: 8
  kernel_size: 3
  features: 128
  contrasts_in_channels: true
  max_cg_iter: 6
  lamda: 0.05
  requires_grad_lamda: true
  batch_norm: false
optim:
  method: Adam
  lr: 0.0005
  step_size: 30
  gamma: 0.1
loss: MixL1L2Loss
learn:
  epochs: 100
  valid_loss_tracker: 12
test:
  checkpoint: null
