
data:
  use_prep_data: False
  data: /data/maple_data.h5  # this's the data saved from /data/prep_maple_data.py
  normalize_kdat: True
  valid_rho: 0.2
  train_rho: 0.4
  repeats: 15
  batch_size: 1

model:
  net: ResNet2D
  N_residual_block: 12
  N_unroll: 8
  features: 128
  contrasts_in_channels: True  # store the contrasts in the channel dimension
  max_cg_iter: 6
  lamda: 0.05
  requires_grad_lamda: True

optim:
  method: Adam
  lr: 0.0005

loss: MixL1L2Loss

learn:
  epochs: 50
  valid_loss_tracker: 12
