method: vae

data:
  # # #
  kdat: /data/1.0mm_21-dir_R1x3_kdat_slice_010.h5
  slice_idx: 10
  coil: /data/1.0mm_21-dir_R1x3_coils.h5
  normalize_kdat: False

test:
  checkpoint: /examples/2024-03-14_vae_1.0mm_21-dir_R1x3_latent-06/train_VAE_Latent06_final.pt
  N_latent: 6
